### ISSUE TITLE
SIGSEGV Error when ip scan of value higher than 210

### ISSUE THREAD

**Issue by rsdmike** [edgexfoundry-holding/device-camera-go#8]
When running the run.sh script with the following contents:
```
cd $GOPATH/src/github.com/edgexfoundry-holding/device-camera-go

# Alternately use go run main.go or launch the binary from 'make build'
#go run main.go  \
./device-camera-go \
 -source onvif:80 \
 -source axis:554 \
 -interval 30 \
 -ip 192.168.100.1-250 \
 -scanduration 15s
```
I get the following error and seems to happen with any upper IP limit over 210:
```
Michaels-MacBook-Pro-5:device-camera-go-1 mike$ ./run.sh
./run.sh: line 1: cd: /Users/mike/go/src/src/github.com/edgexfoundry-holding/device-camera-go: No such file or directory
SourceFlags: [onvif:80 axis:554]
Init: useRegistry: false profile:  confDir: 
Loading configuration from: /Users/mike/Documents/Development/Intel/EdgeX/device-camera-go-1/res/configuration.toml

Bypassing registration in registry...
Calling service.Start.
EnableRemote is false, using local log file
level=INFO ts=2019-05-28T21:13:33.501246Z app=device-camera-go source=init.go:136 msg="Check Metadata service's status ..."
level=INFO ts=2019-05-28T21:13:33.501273Z app=device-camera-go source=init.go:136 msg="Check Data service's status ..."
level=INFO ts=2019-05-28T21:13:33.506133Z app=device-camera-go source=init.go:46 msg="Service clients initialize successful."
level=INFO ts=2019-05-28T21:13:33.512067Z app=device-camera-go source=service.go:146 msg="Device Service device-camera-go exists"
level=INFO ts=2019-05-28T21:13:33.582799Z app=device-camera-go source=edgexservice.go:76 msg="[device-camera-go] - Building flattened port list for scan..."
level=INFO ts=2019-05-28T21:13:33.58317Z app=device-camera-go source=edgexservice.go:76 msg="[device-camera-go] - *** Loaded 2 ONVIF devices from CameraInfoCache... ***"
level=INFO ts=2019-05-28T21:13:33.583428Z app=device-camera-go source=edgexservice.go:76 msg="[device-camera-go] - *** Loaded 0 Axis devices from CameraInfoCache... ***"
level=INFO ts=2019-05-28T21:13:33.583626Z app=device-camera-go source=edgexservice.go:76 msg="[device-camera-go] - Adding CameraDeviceProvider as a proxy/manager EdgeX device"
level=INFO ts=2019-05-28T21:13:33.583741Z app=device-camera-go source=edgexservice.go:76 msg="[device-camera-go] - CameraDiscoveryProvider was previously registered and has EdgeX ID: 26a6ae42-9d6d-4c92-ad43-936807f63059"
level=INFO ts=2019-05-28T21:13:33.583939Z app=device-camera-go source=edgexservice.go:76 msg="[device-camera-go] - \u001b[34mScanning network hosts with 15s timeout...\u001b[0m"
level=INFO ts=2019-05-28T21:13:33.584213Z app=device-camera-go source=edgexservice.go:76 msg="[device-camera-go] - NMAP IP/Mask: 192.168.100.1-250"
level=INFO ts=2019-05-28T21:13:33.584227Z app=device-camera-go source=service.go:117 msg="*Service Start() called, name=device-camera-go, version=0.1"
level=INFO ts=2019-05-28T21:13:33.584599Z app=device-camera-go source=service.go:123 msg="Listening on port: 49990"
level=INFO ts=2019-05-28T21:13:33.585498Z app=device-camera-go source=service.go:124 msg="Service started in: 87.310337ms"
[####################] Scanning 100% complete (12 seconds early)
level=INFO ts=2019-05-28T21:13:38.308028Z app=device-camera-go source=edgexservice.go:76 msg="[device-camera-go] - Scanning 26 discovered hosts for requested camera device signatures..."
level=INFO ts=2019-05-28T21:13:38.310282Z app=device-camera-go source=edgexservice.go:76 msg="[device-camera-go] - Checking for [onvif] camera devices..."
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x16043e2]

goroutine 64 [running]:
github.com/edgexfoundry-holding/device-camera-go/cameradiscoveryprovider.(*CameraDiscoveryProvider).getOnvifCameraDetails(0xc000128480, 0xc0002aa680, 0x12, 0x17a7009, 0x1a, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/mike/Documents/Development/Intel/EdgeX/device-camera-go-1/provider/onvifhandler.go:90 +0x4a2
github.com/edgexfoundry-holding/device-camera-go/cameradiscoveryprovider.(*CameraDiscoveryProvider).getRequestedCameraDetails(0xc000128480, 0x7ffeefbffa53, 0x5, 0x50, 0xc000458a00, 0xf, 0x17a7009, 0x1a, 0xc0002f00c0, 0x1, ...)
        /Users/mike/Documents/Development/Intel/EdgeX/device-camera-go-1/provider/discovercameras.go:489 +0x5ed
github.com/edgexfoundry-holding/device-camera-go/cameradiscoveryprovider.(*CameraDiscoveryProvider).getCameraMetadata(0xc000128480, 0x179a2d2, 0x5, 0xc0001320c0, 0x2, 0x2, 0xc00012c690, 0x17a7009, 0x1a, 0x1d765e8, ...)
        /Users/mike/Documents/Development/Intel/EdgeX/device-camera-go-1/provider/discovercameras.go:416 +0x624
github.com/edgexfoundry-holding/device-camera-go/cameradiscoveryprovider.(*CameraDiscoveryProvider).addCameraDevices(0xc000128480, 0x179a2d2, 0x5, 0x17a39c8, 0x14, 0xc00012c690, 0x46, 0x11, 0x0)
        /Users/mike/Documents/Development/Intel/EdgeX/device-camera-go-1/provider/discovercameras.go:238 +0x1cc
github.com/edgexfoundry-holding/device-camera-go/cameradiscoveryprovider.(*CameraDiscoveryProvider).DiscoverDevices(0xc000128480, 0xc0003ae5c0, 0x7, 0x1e, 0x7ffeefbffa9e, 0x3, 0x7ffeefbffa7e, 0x11, 0x0, 0x0, ...)
        /Users/mike/Documents/Development/Intel/EdgeX/device-camera-go-1/provider/discovercameras.go:212 +0x1ff
github.com/edgexfoundry-holding/device-camera-go/cameradiscoveryprovider.(*CameraDiscoveryProvider).schedulePortScans.func1(0xc000128480, 0xc0003aecd0, 0xc0003ae5c0, 0x7, 0xbf3386ff62cd31e8, 0x54736da, 0x1d569e0)
        /Users/mike/Documents/Development/Intel/EdgeX/device-camera-go-1/provider/edgexservice.go:205 +0x374
created by github.com/edgexfoundry-holding/device-camera-go/cameradiscoveryprovider.(*CameraDiscoveryProvider).schedulePortScans
        /Users/mike/Documents/Development/Intel/EdgeX/device-camera-go-1/provider/edgexservice.go:202 +0xd4
```

**Comment by tobiasmo1** [comment]
@rsdmike this looks to be caused by the response of a non-ONVIF host discovered within that range of your subnet listening on port 80.

Did you successfully run the commands in step 4 of :
https://github.com/edgexfoundry-holding/device-camera-go/blob/master/README.md#preparing-device-camera-go

**Comment by rsdmike** [comment]
Unforunately those commands can't be run on the latest release since there is no vendor/ directory. But yes, I made the changes in the gocache for the code affected.

**Comment by tobiasmo1** [comment]
@rsdmike I discussed with Arthur Tagirov the owner of goonvif package imported by device-camera-go.

Arthur has since [merged the fix](https://github.com/atagirov/goonvif/commit/47cf81244e3c78d11d4e94df4ebb6cd479928f47) on 'master' of his repository so if you rebuild [device-camera-go ('Edinburgh' branch)](https://github.com/tobiasmo1/device-camera-go-1/tree/edinburgh), run `make update` and expect a new git hash in go.sum for the goonvif module.
* https://github.com/atagirov/goonvif

It should work now for both Delhi and Edinburgh versions of device-camera-go, so I will remove the instruction to patch goonvif from the readme markdown.

**Comment by rsdmike** [comment]
That's great! Though, I still have the same error since I had made that patch earlier and updating the hash for that dependency didn't make a difference.

**Comment by tobiasmo1** [comment]
Understood. Will leave this issue open until we can establish root cause.

**Comment by rsdmike** [comment]
Yup, looks like its fixed! Thank you! For reference, was due to a 400 Request from Camera indicating incorrect credentials correct?

**Comment by tobiasmo1** [comment]
Yes, that is correct.
Thank you for helping to track this down.
